### ISSUE TITLE
What is  'your csv' in add_noise function?

### ISSUE THREAD

**Issue by AgentDS** [wnn2000/FedNoRo#3]
Dear authors, I try to run the code for ICH result but have error feedback with 

> Traceback (most recent call last):
  File "train_FedNoRo.py", line 62, in <module>
    y_train_noisy, gamma_s, real_noise_level = add_noise(args, y_train, dict_users)
  File "~/FedNoRo/utils/utils.py", line 32, in add_noise
    df = pd.read_csv("your csv")

The source code is in [add_noise](https://github.com/wnn2000/FedNoRo/blob/0c169a2d64eb323f7c700855df154d4eade13706/utils/utils.py#L17)
<img width="719" alt="Screenshot 2024-01-25 at 2 08 00 AM" src="https://github.com/wnn2000/FedNoRo/assets/19991349/73317b5e-85cf-48c2-ac7e-5ce63f850f13">

I have tried to download `train.csv` and `test.csv` files, as mentioned in [previous issue](https://github.com/wnn2000/FedNoRo/issues/2). Could you please tell me what is the csv file here?

**Comment by wnn2000** [comment]
Hi, thanks for your interest.

This file is actually soft labels of all samples, which are generated by some deep neural models. This way, we can generate harder noise because the soft labels of hard samples are more likely to be divergent from the initial clean labels. 

You may find an example as `.\data\ICH_softlabel.csv`. Training images are aligned with `.\data\train_ICH.csv`. You can also generate your own soft labels for other datasets, e.g., CIFAR.

Best,

Nannan

**Comment by AgentDS** [comment]
Thank you very much! I wonder whether for different runs with different random seeds, should we re-generate this soft label file for each random seed? Or for single dataset, such soft label file is fixed for different runs?

**Comment by wnn2000** [comment]
Hi, you are asking a good question.

Like many existing noise models (e.g., class-conditional noise), the soft label file is used to generate noisy labesl. This is a simulation of the real world situation. So, in my opnien, you should keep the generated noisy labels identical for different runs. To achieve this, the soft label file should be fixed.

Best,
Nannan

**Comment by AgentDS** [comment]
Thank you!

**Comment by wnn2000** [comment]
Siqi, I just find that I have read your articles in Zhihu. They are well-written and I learn a lot.

**Comment by AgentDS** [comment]
Thank you hhhhhh

**Comment by AgentDS** [comment]
another question: have you tried to allow partial client participation for each round? I found [FedNed](https://arxiv.org/abs/2312.12703) claims they used 50% client participation for each round, and one of their baselines is FedNoRo.
